# Generated by Django 5.0.4 on 2024-05-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_agegroup_exercise_gender_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agegroup',
            name='name',
        ),
        migrations.AddField(
            model_name='agegroup',
            name='max_age',
            field=models.IntegerField(default=100, verbose_name='Максимальный возраст'),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='min_age',
            field=models.IntegerField(default=6, verbose_name='Минимальный возраст'),
        ),
    ]
