# Generated by Django 5.0.4 on 2024-05-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_agegroup_name_agegroup_max_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciserating',
            name='score_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exerciserating',
            name='score_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exerciserating',
            name='score_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exerciserating',
            name='score_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exerciserating',
            name='score_9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciserating',
            name='score_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciserating',
            name='score_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciserating',
            name='score_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciserating',
            name='score_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciserating',
            name='score_5',
            field=models.IntegerField(default=0),
        ),
    ]
