# Generated by Django 5.0.4 on 2024-05-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_exerciserating_score_10_exerciserating_score_6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciserating',
            name='score_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciserating',
            name='score_10',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciserating',
            name='score_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciserating',
            name='score_3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciserating',
            name='score_4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciserating',
            name='score_5',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciserating',
            name='score_6',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciserating',
            name='score_7',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciserating',
            name='score_8',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciserating',
            name='score_9',
            field=models.FloatField(default=0),
        ),
    ]
