# Generated by Django 5.0.4 on 2024-05-07 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_exerciserating_score_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseRatingProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_label', models.CharField(max_length=100)),
                ('exercise_grade', models.IntegerField(default=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_ratings', to='myapp.profile')),
            ],
        ),
    ]
