# Generated by Django 5.0.4 on 2024-05-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_exerciseratingprofiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseRatingProfiles',
        ),
    ]
