# Generated by Django 5.0.4 on 2024-05-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_exerciseratingprofiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exercise_ratings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
